name: Build

on:
  push:
    branches:
      - master

jobs:
  llvm-mingw:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up toolchain
      run: |
        mkdir -p $(pwd)/install/llvm-mingw
        curl -Ls https://github.com/mstorsjo/llvm-mingw/releases/download/20231017/llvm-mingw-20231017-ucrt-ubuntu-20.04-x86_64.tar.xz | tar xvJ --strip-components 1 -C $(pwd)/install/llvm-mingw

    - name: Build stage 2
      run: |
        sudo apt-get update && sudo apt-get install ninja-build
        LLVM_CMAKEFLAGS="-DLLVM_ENABLE_LIBXML2=OFF -DLLVM_ENABLE_TERMINFO=OFF -DLLDB_ENABLE_PYTHON=OFF" ./build-llvm.sh $(pwd)/install/llvm-mingw --stage2 --thinlto --disable-clang-tools-extra
        cd install
        DISTRO=ubuntu-$(grep DISTRIB_RELEASE /etc/lsb-release | cut -f 2 -d =)-$(uname -m)
        NAME=llvm-mingw-stage2-lto-ucrt-$DISTRO
        tar -Jcf ../$NAME.tar.xz *

    - uses: actions/upload-artifact@v3
      with:
        name: linux-ucrt-x86_64-toolchain
        path: |
          llvm-mingw-*.tar.xz
        retention-days: 7
